server:
  port: 8082

spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:h2:mem:ms-stock-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
