server:
  port: 8083

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:ms-users-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console